---
title: "Introductory R course"
subtitle: July 2022
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = NA, 
  warning = FALSE,
  message = FALSE)
```

## 1 Getting started

[Slides](https://docs.google.com/presentation/d/1wuaTSNCsBhmRUxFx6ADoxvp8UG28uDqVBL3d50BwUBQ/edit?usp=sharing)

-   Introduction to R and RStudio environment
-   Setting up Projects
-   Libraries and packages
-   File naming conventions

#### Packages

[here](https://here.r-lib.org/)

## 2 Exploratory Data Analysis

[Slides](https://docs.google.com/presentation/d/1Wjx81_gBEk112qsRnbNJ9m9sXUxyF_HE9_71TNXc5Uo/edit?usp=sharing)

-   Reading and writing data
-   Visualizing distributions
-   Patterns in data
-   Missing values

#### Packages
[tidyverse](https://www.tidyverse.org/packages/)

## 3 Data Wrangling
[Slides](https://data-wrangling.netlify.app/#/title-slide)

- Introduction to tidyverse
- Data transformation
- Cleaning data for analysis
- Summarizing datasets

#### Packages
[tidyverse](https://www.tidyverse.org/packages/)     
[gapminder](https://www.rdocumentation.org/packages/gapminder/versions/0.3.0)

## 4 Data Visualization
[Slides](https://cstep-data-viz.netlify.app/#1)

-   Introduction to ggplot package
-   Theory of grammar of graphics
-   Customizable and publication ready plots
-   Common problems with plotting

#### Packages
[tidyverse](https://www.tidyverse.org/packages/)

## 5 Relational Data
[Slides](https://relational-data.netlify.app/#/title-slide)

-   Working with multiple datasets
-   Different kinds of data joins
-   Join problems and pitfalls
-   Set operations with datasets

#### Packages
[tidyverse](https://www.tidyverse.org/packages/)


## 6 Date and Time
[Slides](https://cstep-rcourse-date-and-time.netlify.app/)

-   Creating date/times
-   Introduction lubridate package
-   Manipulating timestamps
-   Arithmetic with date-time data

#### Packages
[tidyverse](https://www.tidyverse.org/packages/)     
[lubridate](https://lubridate.tidyverse.org/)     
[nycflights13](https://cran.r-project.org/web/packages/nycflights13/index.html)     
[openair](https://davidcarslaw.github.io/openair/)

## 7 Iterations & Functions
[Slides](https://cstep-iterations.netlify.app/#/title-slide)

-   Introduction to functions
-   for loops
-   Introduction to purrr package
-   Best practices for efficient code

#### Packages
[tidyverse](https://www.tidyverse.org/packages/)   
[gapminder](https://www.rdocumentation.org/packages/gapminder/versions/0.3.0)

## 8 Statistics & Modelling
[Slides](https://cstep-stats.netlify.app/)

#### Packages (new)
[gtsummary](https://www.danieldsjoberg.com/gtsummary/)  
[flextable](https://ardata-fr.github.io/flextable-book/)  
[broom](https://broom.tidymodels.org/)  


-   Summary statistics
-   Linear Regression
-   Working with multiple models
-   Brief introduction to Machine Learning

## 9 Spatial Analysis
[Slides](https://r-course-spatial-analysis.netlify.app/#1)

-   Introduction to coordinate systems
-   Introduction to sf and raster packages
-   Making maps in R
-   Spatial data analysis in R

#### Packages
[sf](https://r-spatial.github.io/sf/)  
[raster](https://rspatial.org/raster/pkg/index.html)  
[leaflet](https://rstudio.github.io/leaflet/)  
[ggspatial](https://paleolimbot.github.io/ggspatial/)  


## 10 Reporting with RMarkdown
[Slides](cstep-rmd.netlify.app)

-   Creating reproducible reports
-   Themes and formatting
-   Automated reports using parameters
-   Introduction to Xaringan package

#### Packages
[glue](https://glue.tidyverse.org/)
[gapminder](https://www.rdocumentation.org/packages/gapminder/versions/0.3.0)
[tidyverse](https://www.tidyverse.org/packages/)  

